// Auto-generated for Main Street Movies - covers ALL countries from register page
export const countriesWithCurrency = [
  { code: '+93', flag: '🇦🇫', name: 'Afghanistan', currency: 'AFN', symbol: '؋' },
  { code: '+355', flag: '🇦🇱', name: 'Albania', currency: 'ALL', symbol: 'L' },
  { code: '+213', flag: '🇩🇿', name: 'Algeria', currency: 'DZD', symbol: 'د.ج' },
  { code: '+1 684', flag: '🇦🇸', name: 'American Samoa', currency: 'USD', symbol: '$' },
  { code: '+376', flag: '🇦🇩', name: 'Andorra', currency: 'EUR', symbol: '€' },
  { code: '+244', flag: '🇦🇴', name: 'Angola', currency: 'AOA', symbol: 'Kz' },
  { code: '+1 264', flag: '🇦🇮', name: 'Anguilla', currency: 'XCD', symbol: '$' },
  { code: '+672', flag: '🇦🇶', name: 'Antarctica', currency: 'USD', symbol: '$' },
  { code: '+1 268', flag: '🇦🇬', name: 'Antigua and Barbuda', currency: 'XCD', symbol: '$' },
  { code: '+54', flag: '🇦🇷', name: 'Argentina', currency: 'ARS', symbol: '$' },
  { code: '+374', flag: '🇦🇲', name: 'Armenia', currency: 'AMD', symbol: '֏' },
  { code: '+297', flag: '🇦🇼', name: 'Aruba', currency: 'AWG', symbol: 'ƒ' },
  { code: '+61', flag: '🇦🇺', name: 'Australia', currency: 'AUD', symbol: 'A$' },
  { code: '+43', flag: '🇦🇹', name: 'Austria', currency: 'EUR', symbol: '€' },
  { code: '+994', flag: '🇦🇿', name: 'Azerbaijan', currency: 'AZN', symbol: '₼' },
  { code: '+1 242', flag: '🇧🇸', name: 'Bahamas', currency: 'BSD', symbol: '$' },
  { code: '+973', flag: '🇧🇭', name: 'Bahrain', currency: 'BHD', symbol: '.د.ب' },
  { code: '+880', flag: '🇧🇩', name: 'Bangladesh', currency: 'BDT', symbol: '৳' },
  { code: '+1 246', flag: '🇧🇧', name: 'Barbados', currency: 'BBD', symbol: '$' },
  { code: '+375', flag: '🇧🇾', name: 'Belarus', currency: 'BYN', symbol: 'Br' },
  { code: '+32', flag: '🇧🇪', name: 'Belgium', currency: 'EUR', symbol: '€' },
  { code: '+501', flag: '🇧🇿', name: 'Belize', currency: 'BZD', symbol: 'BZ$' },
  { code: '+229', flag: '🇧🇯', name: 'Benin', currency: 'XOF', symbol: 'CFA' },
  { code: '+1 441', flag: '🇧🇲', name: 'Bermuda', currency: 'BMD', symbol: '$' },
  { code: '+975', flag: '🇧🇹', name: 'Bhutan', currency: 'BTN', symbol: 'Nu.' },
  { code: '+591', flag: '🇧🇴', name: 'Bolivia', currency: 'BOB', symbol: 'Bs.' },
  { code: '+387', flag: '🇧🇦', name: 'Bosnia and Herzegovina', currency: 'BAM', symbol: 'KM' },
  { code: '+267', flag: '🇧🇼', name: 'Botswana', currency: 'BWP', symbol: 'P' },
  { code: '+55', flag: '🇧🇷', name: 'Brazil', currency: 'BRL', symbol: 'R$' },
  { code: '+1 284', flag: '🇻🇬', name: 'British Virgin Islands', currency: 'USD', symbol: '$' },
  { code: '+673', flag: '🇧🇳', name: 'Brunei', currency: 'BND', symbol: '$' },
  { code: '+359', flag: '🇧🇬', name: 'Bulgaria', currency: 'BGN', symbol: 'лв' },
  { code: '+226', flag: '🇧🇫', name: 'Burkina Faso', currency: 'XOF', symbol: 'CFA' },
  { code: '+257', flag: '🇧🇮', name: 'Burundi', currency: 'BIF', symbol: 'FBu' },
  { code: '+855', flag: '🇰🇭', name: 'Cambodia', currency: 'KHR', symbol: '៛' },
  { code: '+237', flag: '🇨🇲', name: 'Cameroon', currency: 'XAF', symbol: 'FCFA' },
  { code: '+1', flag: '🇨🇦', name: 'Canada', currency: 'CAD', symbol: 'C$' },
  { code: '+238', flag: '🇨🇻', name: 'Cape Verde', currency: 'CVE', symbol: '$' },
  { code: '+1 345', flag: '🇰🇾', name: 'Cayman Islands', currency: 'KYD', symbol: '$' },
  { code: '+236', flag: '🇨🇫', name: 'Central African Republic', currency: 'XAF', symbol: 'FCFA' },
  { code: '+235', flag: '🇹🇩', name: 'Chad', currency: 'XAF', symbol: 'FCFA' },
  { code: '+56', flag: '🇨🇱', name: 'Chile', currency: 'CLP', symbol: '$' },
  { code: '+86', flag: '🇨🇳', name: 'China', currency: 'CNY', symbol: '¥' },
  { code: '+57', flag: '🇨🇴', name: 'Colombia', currency: 'COP', symbol: '$' },
  { code: '+269', flag: '🇰🇲', name: 'Comoros', currency: 'KMF', symbol: 'CF' },
  { code: '+243', flag: '🇨🇬', name: 'Congo', currency: 'XAF', symbol: 'FCFA' },
  { code: '+243', flag: '🇨🇩', name: 'Congo DRC', currency: 'CDF', symbol: 'FC' },
  { code: '+682', flag: '🇨🇰', name: 'Cook Islands', currency: 'NZD', symbol: '$' },
  { code: '+506', flag: '🇨🇷', name: 'Costa Rica', currency: 'CRC', symbol: '₡' },
  { code: '+385', flag: '🇭🇷', name: 'Croatia', currency: 'EUR', symbol: '€' },
  { code: '+53', flag: '🇨🇺', name: 'Cuba', currency: 'CUP', symbol: '₱' },
  { code: '+599', flag: '🇨🇼', name: 'Curacao', currency: 'ANG', symbol: 'ƒ' },
  { code: '+357', flag: '🇨🇾', name: 'Cyprus', currency: 'EUR', symbol: '€' },
  { code: '+420', flag: '🇨🇿', name: 'Czech Republic', currency: 'CZK', symbol: 'Kč' },
  { code: '+45', flag: '🇩🇰', name: 'Denmark', currency: 'DKK', symbol: 'kr' },
  { code: '+253', flag: '🇩🇯', name: 'Djibouti', currency: 'DJF', symbol: 'Fdj' },
  { code: '+1 767', flag: '🇩🇲', name: 'Dominica', currency: 'XCD', symbol: '$' },
  { code: '+1 809', flag: '🇩🇴', name: 'Dominican Republic', currency: 'DOP', symbol: 'RD$' },
  { code: '+593', flag: '🇪🇨', name: 'Ecuador', currency: 'USD', symbol: '$' },
  { code: '+20', flag: '🇪🇬', name: 'Egypt', currency: 'EGP', symbol: '£' },
  { code: '+503', flag: '🇸🇻', name: 'El Salvador', currency: 'USD', symbol: '$' },
  { code: '+240', flag: '🇬🇶', name: 'Equatorial Guinea', currency: 'XAF', symbol: 'FCFA' },
  { code: '+291', flag: '🇪🇷', name: 'Eritrea', currency: 'ERN', symbol: 'Nfk' },
  { code: '+372', flag: '🇪🇪', name: 'Estonia', currency: 'EUR', symbol: '€' },
  { code: '+268', flag: '🇸🇿', name: 'Eswatini', currency: 'SZL', symbol: 'E' },
  { code: '+251', flag: '🇪🇹', name: 'Ethiopia', currency: 'ETB', symbol: 'Br' },
  { code: '+500', flag: '🇫🇰', name: 'Falkland Islands', currency: 'FKP', symbol: '£' },
  { code: '+298', flag: '🇫🇴', name: 'Faroe Islands', currency: 'DKK', symbol: 'kr' },
  { code: '+679', flag: '🇫🇯', name: 'Fiji', currency: 'FJD', symbol: '$' },
  { code: '+358', flag: '🇫🇮', name: 'Finland', currency: 'EUR', symbol: '€' },
  { code: '+33', flag: '🇫🇷', name: 'France', currency: 'EUR', symbol: '€' },
  { code: '+689', flag: '🇵🇫', name: 'French Polynesia', currency: 'XPF', symbol: '₣' },
  { code: '+241', flag: '🇬🇦', name: 'Gabon', currency: 'XAF', symbol: 'FCFA' },
  { code: '+220', flag: '🇬🇲', name: 'Gambia', currency: 'GMD', symbol: 'D' },
  { code: '+995', flag: '🇬🇪', name: 'Georgia', currency: 'GEL', symbol: '₾' },
  { code: '+49', flag: '🇩🇪', name: 'Germany', currency: 'EUR', symbol: '€' },
  { code: '+233', flag: '🇬🇭', name: 'Ghana', currency: 'GHS', symbol: '₵' },
  { code: '+350', flag: '🇬🇮', name: 'Gibraltar', currency: 'GIP', symbol: '£' },
  { code: '+30', flag: '🇬🇷', name: 'Greece', currency: 'EUR', symbol: '€' },
  { code: '+299', flag: '🇬🇱', name: 'Greenland', currency: 'DKK', symbol: 'kr' },
  { code: '+1 473', flag: '🇬🇩', name: 'Grenada', currency: 'XCD', symbol: '$' },
  { code: '+1 671', flag: '🇬🇺', name: 'Guam', currency: 'USD', symbol: '$' },
  { code: '+502', flag: '🇬🇹', name: 'Guatemala', currency: 'GTQ', symbol: 'Q' },
  { code: '+224', flag: '🇬🇳', name: 'Guinea', currency: 'GNF', symbol: 'FG' },
  { code: '+245', flag: '🇬🇼', name: 'Guinea-Bissau', currency: 'XOF', symbol: 'CFA' },
  { code: '+592', flag: '🇬🇾', name: 'Guyana', currency: 'GYD', symbol: '$' },
  { code: '+509', flag: '🇭🇹', name: 'Haiti', currency: 'HTG', symbol: 'G' },
  { code: '+504', flag: '🇭🇳', name: 'Honduras', currency: 'HNL', symbol: 'L' },
  { code: '+852', flag: '🇭🇰', name: 'Hong Kong', currency: 'HKD', symbol: 'HK$' },
  { code: '+36', flag: '🇭🇺', name: 'Hungary', currency: 'HUF', symbol: 'Ft' },
  { code: '+354', flag: '🇮🇸', name: 'Iceland', currency: 'ISK', symbol: 'kr' },
  { code: '+91', flag: '🇮🇳', name: 'India', currency: 'INR', symbol: '₹' },
  { code: '+62', flag: '🇮🇩', name: 'Indonesia', currency: 'IDR', symbol: 'Rp' },
  { code: '+98', flag: '🇮🇷', name: 'Iran', currency: 'IRR', symbol: '﷼' },
  { code: '+964', flag: '🇮🇶', name: 'Iraq', currency: 'IQD', symbol: 'ع.د' },
  { code: '+353', flag: '🇮🇪', name: 'Ireland', currency: 'EUR', symbol: '€' },
  { code: '+972', flag: '🇮🇱', name: 'Israel', currency: 'ILS', symbol: '₪' },
  { code: '+39', flag: '🇮🇹', name: 'Italy', currency: 'EUR', symbol: '€' },
  { code: '+1 876', flag: '🇯🇲', name: 'Jamaica', currency: 'JMD', symbol: 'J$' },
  { code: '+81', flag: '🇯🇵', name: 'Japan', currency: 'JPY', symbol: '¥' },
  { code: '+962', flag: '🇯🇴', name: 'Jordan', currency: 'JOD', symbol: 'JD' },
  { code: '+7', flag: '🇰🇿', name: 'Kazakhstan', currency: 'KZT', symbol: '₸' },
  { code: '+254', flag: '🇰🇪', name: 'Kenya', currency: 'KES', symbol: 'KSh' },
  { code: '+686', flag: '🇰🇮', name: 'Kiribati', currency: 'AUD', symbol: 'A$' },
  { code: '+850', flag: '🇰🇵', name: 'North Korea', currency: 'KPW', symbol: '₩' },
  { code: '+82', flag: '🇰🇷', name: 'South Korea', currency: 'KRW', symbol: '₩' },
  { code: '+965', flag: '🇰🇼', name: 'Kuwait', currency: 'KWD', symbol: 'KD' },
  { code: '+996', flag: '🇰🇬', name: 'Kyrgyzstan', currency: 'KGS', symbol: 'лв' },
  { code: '+856', flag: '🇱🇦', name: 'Laos', currency: 'LAK', symbol: '₭' },
  { code: '+371', flag: '🇱🇻', name: 'Latvia', currency: 'EUR', symbol: '€' },
  { code: '+961', flag: '🇱🇧', name: 'Lebanon', currency: 'LBP', symbol: '£' },
  { code: '+266', flag: '🇱🇸', name: 'Lesotho', currency: 'LSL', symbol: 'M' },
  { code: '+231', flag: '🇱🇷', name: 'Liberia', currency: 'LRD', symbol: '$' },
  { code: '+218', flag: '🇱🇾', name: 'Libya', currency: 'LYD', symbol: 'LD' },
  { code: '+423', flag: '🇱🇮', name: 'Liechtenstein', currency: 'CHF', symbol: 'CHF' },
  { code: '+370', flag: '🇱🇹', name: 'Lithuania', currency: 'EUR', symbol: '€' },
  { code: '+352', flag: '🇱🇺', name: 'Luxembourg', currency: 'EUR', symbol: '€' },
  { code: '+853', flag: '🇲🇴', name: 'Macao', currency: 'MOP', symbol: 'MOP$' },
  { code: '+389', flag: '🇲🇰', name: 'North Macedonia', currency: 'MKD', symbol: 'ден' },
  { code: '+261', flag: '🇲🇬', name: 'Madagascar', currency: 'MGA', symbol: 'Ar' },
  { code: '+265', flag: '🇲🇼', name: 'Malawi', currency: 'MWK', symbol: 'MK' },
  { code: '+60', flag: '🇲🇾', name: 'Malaysia', currency: 'MYR', symbol: 'RM' },
  { code: '+960', flag: '🇲🇻', name: 'Maldives', currency: 'MVR', symbol: 'Rf' },
  { code: '+223', flag: '🇲🇱', name: 'Mali', currency: 'XOF', symbol: 'CFA' },
  { code: '+356', flag: '🇲🇹', name: 'Malta', currency: 'EUR', symbol: '€' },
  { code: '+692', flag: '🇲🇭', name: 'Marshall Islands', currency: 'USD', symbol: '$' },
  { code: '+222', flag: '🇲🇷', name: 'Mauritania', currency: 'MRU', symbol: 'UM' },
  { code: '+230', flag: '🇲🇺', name: 'Mauritius', currency: 'MUR', symbol: '₨' },
  { code: '+52', flag: '🇲🇽', name: 'Mexico', currency: 'MXN', symbol: '$' },
  { code: '+691', flag: '🇫🇲', name: 'Micronesia', currency: 'USD', symbol: '$' },
  { code: '+373', flag: '🇲🇩', name: 'Moldova', currency: 'MDL', symbol: 'L' },
  { code: '+377', flag: '🇲🇨', name: 'Monaco', currency: 'EUR', symbol: '€' },
  { code: '+976', flag: '🇲🇳', name: 'Mongolia', currency: 'MNT', symbol: '₮' },
  { code: '+382', flag: '🇲🇪', name: 'Montenegro', currency: 'EUR', symbol: '€' },
  { code: '+1 664', flag: '🇲🇸', name: 'Montserrat', currency: 'XCD', symbol: '$' },
  { code: '+212', flag: '🇲🇦', name: 'Morocco', currency: 'MAD', symbol: 'DH' },
  { code: '+258', flag: '🇲🇿', name: 'Mozambique', currency: 'MZN', symbol: 'MT' },
  { code: '+95', flag: '🇲🇲', name: 'Myanmar', currency: 'MMK', symbol: 'K' },
  { code: '+264', flag: '🇳🇦', name: 'Namibia', currency: 'NAD', symbol: '$' },
  { code: '+674', flag: '🇳🇷', name: 'Nauru', currency: 'AUD', symbol: 'A$' },
  { code: '+977', flag: '🇳🇵', name: 'Nepal', currency: 'NPR', symbol: '₨' },
  { code: '+31', flag: '🇳🇱', name: 'Netherlands', currency: 'EUR', symbol: '€' },
  { code: '+687', flag: '🇳🇨', name: 'New Caledonia', currency: 'XPF', symbol: '₣' },
  { code: '+64', flag: '🇳🇿', name: 'New Zealand', currency: 'NZD', symbol: '$' },
  { code: '+505', flag: '🇳🇮', name: 'Nicaragua', currency: 'NIO', symbol: 'C$' },
  { code: '+227', flag: '🇳🇪', name: 'Niger', currency: 'XOF', symbol: 'CFA' },
  { code: '+234', flag: '🇳🇬', name: 'Nigeria', currency: 'NGN', symbol: '₦' },
  { code: '+683', flag: '🇳🇺', name: 'Niue', currency: 'NZD', symbol: '$' },
  { code: '+1 670', flag: '🇲🇵', name: 'Northern Mariana Islands', currency: 'USD', symbol: '$' },
  { code: '+47', flag: '🇳🇴', name: 'Norway', currency: 'NOK', symbol: 'kr' },
  { code: '+968', flag: '🇴🇲', name: 'Oman', currency: 'OMR', symbol: '﷼' },
  { code: '+92', flag: '🇵🇰', name: 'Pakistan', currency: 'PKR', symbol: '₨' },
  { code: '+680', flag: '🇵🇼', name: 'Palau', currency: 'USD', symbol: '$' },
  { code: '+970', flag: '🇵🇸', name: 'Palestine', currency: 'ILS', symbol: '₪' },
  { code: '+507', flag: '🇵🇦', name: 'Panama', currency: 'PAB', symbol: 'B/.' },
  { code: '+675', flag: '🇵🇬', name: 'Papua New Guinea', currency: 'PGK', symbol: 'K' },
  { code: '+595', flag: '🇵🇾', name: 'Paraguay', currency: 'PYG', symbol: 'Gs' },
  { code: '+51', flag: '🇵🇪', name: 'Peru', currency: 'PEN', symbol: 'S/.' },
  { code: '+63', flag: '🇵🇭', name: 'Philippines', currency: 'PHP', symbol: '₱' },
  { code: '+48', flag: '🇵🇱', name: 'Poland', currency: 'PLN', symbol: 'zł' },
  { code: '+351', flag: '🇵🇹', name: 'Portugal', currency: 'EUR', symbol: '€' },
  { code: '+1 787', flag: '🇵🇷', name: 'Puerto Rico', currency: 'USD', symbol: '$' },
  { code: '+974', flag: '🇶🇦', name: 'Qatar', currency: 'QAR', symbol: 'QR' },
  { code: '+40', flag: '🇷🇴', name: 'Romania', currency: 'RON', symbol: 'lei' },
  { code: '+7', flag: '🇷🇺', name: 'Russia', currency: 'RUB', symbol: '₽' },
  { code: '+250', flag: '🇷🇼', name: 'Rwanda', currency: 'RWF', symbol: 'RWF' },
  { code: '+1 869', flag: '🇰🇳', name: 'Saint Kitts and Nevis', currency: 'XCD', symbol: '$' },
  { code: '+1 758', flag: '🇱🇨', name: 'Saint Lucia', currency: 'XCD', symbol: '$' },
  { code: '+1 784', flag: '🇻🇨', name: 'Saint Vincent', currency: 'XCD', symbol: '$' },
  { code: '+685', flag: '🇼🇸', name: 'Samoa', currency: 'WST', symbol: 'WS$' },
  { code: '+378', flag: '🇸🇲', name: 'San Marino', currency: 'EUR', symbol: '€' },
  { code: '+239', flag: '🇸🇹', name: 'Sao Tome and Principe', currency: 'STN', symbol: 'Db' },
  { code: '+966', flag: '🇸🇦', name: 'Saudi Arabia', currency: 'SAR', symbol: '﷼' },
  { code: '+221', flag: '🇸🇳', name: 'Senegal', currency: 'XOF', symbol: 'CFA' },
  { code: '+381', flag: '🇷🇸', name: 'Serbia', currency: 'RSD', symbol: 'дин.' },
  { code: '+248', flag: '🇸🇨', name: 'Seychelles', currency: 'SCR', symbol: '₨' },
  { code: '+232', flag: '🇸🇱', name: 'Sierra Leone', currency: 'SLL', symbol: 'Le' },
  { code: '+65', flag: '🇸🇬', name: 'Singapore', currency: 'SGD', symbol: 'S$' },
  { code: '+1 721', flag: '🇸🇽', name: 'Sint Maarten', currency: 'ANG', symbol: 'ƒ' },
  { code: '+421', flag: '🇸🇰', name: 'Slovakia', currency: 'EUR', symbol: '€' },
  { code: '+386', flag: '🇸🇮', name: 'Slovenia', currency: 'EUR', symbol: '€' },
  { code: '+677', flag: '🇸🇧', name: 'Solomon Islands', currency: 'SBD', symbol: '$' },
  { code: '+252', flag: '🇸🇴', name: 'Somalia', currency: 'SOS', symbol: 'S' },
  { code: '+27', flag: '🇿🇦', name: 'South Africa', currency: 'ZAR', symbol: 'R' },
  { code: '+211', flag: '🇸🇸', name: 'South Sudan', currency: 'SSP', symbol: '£' },
  { code: '+34', flag: '🇪🇸', name: 'Spain', currency: 'EUR', symbol: '€' },
  { code: '+94', flag: '🇱🇰', name: 'Sri Lanka', currency: 'LKR', symbol: '₨' },
  { code: '+249', flag: '🇸🇩', name: 'Sudan', currency: 'SDG', symbol: 'ج.س.' },
  { code: '+597', flag: '🇸🇷', name: 'Suriname', currency: 'SRD', symbol: '$' },
  { code: '+46', flag: '🇸🇪', name: 'Sweden', currency: 'SEK', symbol: 'kr' },
  { code: '+41', flag: '🇨🇭', name: 'Switzerland', currency: 'CHF', symbol: 'CHF' },
  { code: '+963', flag: '🇸🇾', name: 'Syria', currency: 'SYP', symbol: '£' },
  { code: '+886', flag: '🇹🇼', name: 'Taiwan', currency: 'TWD', symbol: 'NT$' },
  { code: '+992', flag: '🇹🇯', name: 'Tajikistan', currency: 'TJS', symbol: 'SM' },
  { code: '+255', flag: '🇹🇿', name: 'Tanzania', currency: 'TZS', symbol: 'TSh' },
  { code: '+66', flag: '🇹🇭', name: 'Thailand', currency: 'THB', symbol: '฿' },
  { code: '+670', flag: '🇹🇱', name: 'Timor-Leste', currency: 'USD', symbol: '$' },
  { code: '+228', flag: '🇹🇬', name: 'Togo', currency: 'XOF', symbol: 'CFA' },
  { code: '+690', flag: '🇹🇰', name: 'Tokelau', currency: 'NZD', symbol: '$' },
  { code: '+676', flag: '🇹🇴', name: 'Tonga', currency: 'TOP', symbol: 'T$' },
  { code: '+1 868', flag: '🇹🇹', name: 'Trinidad and Tobago', currency: 'TTD', symbol: 'TT$' },
  { code: '+216', flag: '🇹🇳', name: 'Tunisia', currency: 'TND', symbol: 'د.ت' },
  { code: '+90', flag: '🇹🇷', name: 'Turkey', currency: 'TRY', symbol: '₺' },
  { code: '+993', flag: '🇹🇲', name: 'Turkmenistan', currency: 'TMT', symbol: 'T' },
  { code: '+1 649', flag: '🇹🇨', name: 'Turks and Caicos', currency: 'USD', symbol: '$' },
  { code: '+688', flag: '🇹🇻', name: 'Tuvalu', currency: 'AUD', symbol: 'A$' },
  { code: '+256', flag: '🇺🇬', name: 'Uganda', currency: 'UGX', symbol: 'USh' },
  { code: '+380', flag: '🇺🇦', name: 'Ukraine', currency: 'UAH', symbol: '₴' },
  { code: '+971', flag: '🇦🇪', name: 'UAE', currency: 'AED', symbol: 'AED' },
  { code: '+44', flag: '🇬🇧', name: 'United Kingdom', currency: 'GBP', symbol: '£' },
  { code: '+1', flag: '🇺🇸', name: 'United States', currency: 'USD', symbol: '$' },
  { code: '+598', flag: '🇺🇾', name: 'Uruguay', currency: 'UYU', symbol: '$U' },
  { code: '+998', flag: '🇺🇿', name: 'Uzbekistan', currency: 'UZS', symbol: 'лв' },
  { code: '+678', flag: '🇻🇺', name: 'Vanuatu', currency: 'VUV', symbol: 'VT' },
  { code: '+379', flag: '🇻🇦', name: 'Vatican City', currency: 'EUR', symbol: '€' },
  { code: '+58', flag: '🇻🇪', name: 'Venezuela', currency: 'VES', symbol: 'Bs.' },
  { code: '+84', flag: '🇻🇳', name: 'Vietnam', currency: 'VND', symbol: '₫' },
  { code: '+1 340', flag: '🇻🇮', name: 'US Virgin Islands', currency: 'USD', symbol: '$' },
  { code: '+681', flag: '🇼🇫', name: 'Wallis and Futuna', currency: 'XPF', symbol: '₣' },
  { code: '+967', flag: '🇾🇪', name: 'Yemen', currency: 'YER', symbol: '﷼' },
  { code: '+260', flag: '🇿🇲', name: 'Zambia', currency: 'ZMW', symbol: 'ZK' },
  { code: '+263', flag: '🇿🇼', name: 'Zimbabwe', currency: 'ZWL', symbol: '$' },
]

export function detectCountry(phoneOrCode){
  const clean = String(phoneOrCode).replace(/\D/g,'')
  // match longest code first
  const sorted = [...countriesWithCurrency].sort((a,b)=>b.code.replace(/\D/g,'').length - a.code.replace(/\D/g,'').length)
  for(let c of sorted){
    const ccode = c.code.replace(/\D/g,'')
    if(clean.startsWith(ccode)) return c
  }
  return countriesWithCurrency.find(c=>c.name==='Uganda')
}